version: '3.4'
networks:
  local:
    name: fabric_odins

services:
  chainREST.odins.com:
    image: chainapi/node-web-app
    restart: always
    ports:
      - "3000:3000"
#    extra_hosts:
#      - peer0.org1.odins.com:127.0.0.1
#      - orderer.odins.com:127.0.0.1
#      - ca.org1.odins.com:127.0.0.1
    restart: always
    networks:
      - local