@startuml

skinparam monochrome false
skinparam shadowing true
skinparam roundcorner 10

participant "XACML\n(PAP)"
participant "DLT"

group Authorisation DCapBAC - Access Control
    
    "XACML\n(PAP)" -> "DLT" : STORE_HASH(Domain)

end

@enduml
